#!/usr/bin/python

import serial
import sys


#serial_port_path = '/dev/ttyACM0'
#signal_to_write = '1'

serial_port_path = sys.argv[1]
signal_to_write = sys.argv[2]

serial_port = serial.Serial(serial_port_path, 9600)
serial_port.write(signal_to_write)
serial_port.close()
